[package]
name = "akasa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bytes = "1.2.1"
clap = { version = "4.0.26", features = ["derive"] }
dashmap = "5.4.0"
env_logger = "0.9.3"
flume = "0.10.14"
futures-lite = "1.12.0"
glommio = "0.7.0"
hashbrown = "0.13.1"
json5 = "0.4.1"
log = "0.4.17"
mqtt-protocol = { version = "0.11.2" }
num_cpus = "1.14.0"
parking_lot = "0.12.1"
# rhai = { version = "1.11.0", features = ["decimal"] }
# jsonwebtoken = "8.2.0"
# jwt-simple = "0.11.2"
serde = { version = "1.0.147", features = ["derive"] }
thiserror = "1.0.37"
