
[workspace]
members = ["akasa-core", "akasa"]
resolver = "2"

# [profile.release]
# debug = true

# ==== Optimize for binary size ====
# opt-level = 's'
# lto = true
# codegen-units = 1
# strip = true
